name: Deploy dev preview to Heroku (SRA)

on:
  push:
    branches-ignore:
      - main
    paths:
      - "Project/mood-tracker/**"
      - ".github/workflows/mood-tracker-dev.yml"

jobs:
  deploy:
    if: github.repository != 'SuleymanDemirelKazakhstan/diploma-project-charming-hamsters'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_KEY}}
          envs: GITHUB_REF_NAME
          script: |
            git clone https://github.com/KaskelenValley/Memento.git ~/Memento
            cd ~/Memento/Project/mood-tracker
            git checkout $GITHUB_REF_NAME
            git lfs pull
            poetry install --no-dev
            uvicorn main:app --host 0.0.0.0 --port 8080
