name: Deploy dev preview to Heroku (SRA)

on:
  push:
    branches-ignore:
      - main
    paths:
      - "Project/mood-tracker/**"
      - ".github/workflows/mood-tracker-dev.yml"

jobs:
  deploy:
    if: github.repository != 'SuleymanDemirelKazakhstan/diploma-project-charming-hamsters'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DO_HOST}}
          username: root
          password: ${{secrets.DO_PASSWORD}}
          envs: GITHUB_REF_NAME
          script: |
            if [ ! -d "$HOME/app" ]; then
              git clone https://github.com/KaskelenValley/Memento.git ~/app
            else
              cd ~/app
              git pull
            fi
            cd ./Project/mood-tracker
            git checkout $GITHUB_REF_NAME
            docker container rm -f $(docker container ls -aq) || true
            docker build -t mood-tracker-dev .
            docker run --rm -v weights:weights -p 8080:8080 mood-tracker-dev
